Repository sirjonasxx/G-ExtensionStore, pull requests merged in 2023-04, with the labels that each got.

#125 feat: EventSender 1.4
  store/extensions/EventSender/extension.json
  store/extensions/EventSender/extension.zip
Labels: Native, Update

#128 average checker 2.0.1
  store/extensions/average-checker/extension.json
  store/extensions/average-checker/extension.zip
Labels: G-Node, Update

#131 Remove average-checker
  store/extensions/average-checker/extension.json
Labels: G-Node, Removed extension

#132 feat: Market Utils v2.0
  store/extensions/Market Utils/extension.json
  store/extensions/Market Utils/extension.zip
  store/extensions/Market Utils/screenshot.png
Labels: Native, Update
